export type OrbitType = 'SSO' | 'LEO' | 'GEO';

export interface SatelliteProduct {
  id: string;
  name: string;
  code: string;
  category: string;
  missionType: string;
  payloadType: string;
  orbitType: OrbitType;
  agencies: string[];
  region: string;
  launchYear: number;
  orbitAltitudeKm?: number;
  inclinationDeg?: number;
  massKg?: number;
  powerW?: number;
  designLifeYears?: number;
  resolutionM?: number;
  keywords?: string[];
}

export const HOT_KEYWORDS = [
  'Sentinel-2',
  'Sentinel-5P',
  'Landsat',
  'GOES',
  'Himawari',
  'MetOp',
  'Jason-3',
  'Sentinel-6',
  'ICESat-2',
  'GRACE',
  'CloudSat',
  'CALIPSO',
  'GPM',
  'OCO-2',
  'SMAP',
  'SWOT',
];

export const SATELLITE_PRODUCTS: SatelliteProduct[] = [
  {
    id: 's1a',
    name: 'Sentinel-1A (哨兵-1A)',
    code: 'S1A',
    category: '对地观测',
    missionType: 'C波段SAR雷达',
    payloadType: 'SAR',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2014,
    orbitAltitudeKm: 693,
    massKg: 2185,
    resolutionM: 5,
    designLifeYears: 7,
    keywords: ['Sentinel-1', '哨兵1', 'SAR', '雷达'],
  },
  {
    id: 's1b',
    name: 'Sentinel-1B (哨兵-1B)',
    code: 'S1B',
    category: '对地观测',
    missionType: 'C波段SAR雷达',
    payloadType: 'SAR',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2016,
    orbitAltitudeKm: 693,
    massKg: 2185,
    resolutionM: 5,
    designLifeYears: 7,
    keywords: ['Sentinel-1', '哨兵1', 'SAR', '雷达'],
  },
  {
    id: 's1c',
    name: 'Sentinel-1C (哨兵-1C)',
    code: 'S1C',
    category: '对地观测',
    missionType: 'C波段SAR雷达',
    payloadType: 'SAR',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2024,
    orbitAltitudeKm: 693,
    massKg: 2185,
    resolutionM: 5,
    designLifeYears: 7,
    keywords: ['Sentinel-1', '哨兵1', 'SAR', '雷达'],
  },
  {
    id: 's1d',
    name: 'Sentinel-1D (哨兵-1D)',
    code: 'S1D',
    category: '对地观测',
    missionType: 'C波段SAR雷达',
    payloadType: 'SAR',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2025,
    orbitAltitudeKm: 693,
    massKg: 2185,
    resolutionM: 5,
    designLifeYears: 7,
    keywords: ['Sentinel-1', '哨兵1', 'SAR', '雷达'],
  },
  {
    id: 's2a',
    name: 'Sentinel-2A (哨兵-2A)',
    code: 'S2A',
    category: '对地观测',
    missionType: '多光谱光学遥感',
    payloadType: '多光谱成像',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2015,
    orbitAltitudeKm: 786,
    massKg: 1140,
    powerW: 1700,
    resolutionM: 10,
    designLifeYears: 7,
    keywords: ['Sentinel-2', '哨兵2', 'MSI', '光学'],
  },
  {
    id: 's2b',
    name: 'Sentinel-2B (哨兵-2B)',
    code: 'S2B',
    category: '对地观测',
    missionType: '多光谱光学遥感',
    payloadType: '多光谱成像',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2017,
    orbitAltitudeKm: 786,
    massKg: 1140,
    powerW: 1700,
    resolutionM: 10,
    designLifeYears: 7,
    keywords: ['Sentinel-2', '哨兵2', 'MSI', '光学'],
  },
  {
    id: 's2c',
    name: 'Sentinel-2C (哨兵-2C)',
    code: 'S2C',
    category: '对地观测',
    missionType: '多光谱光学遥感',
    payloadType: '多光谱成像',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2024,
    orbitAltitudeKm: 786,
    massKg: 1140,
    powerW: 1700,
    resolutionM: 10,
    designLifeYears: 7,
    keywords: ['Sentinel-2', '哨兵2', 'MSI', '光学'],
  },
  {
    id: 's3a',
    name: 'Sentinel-3A (哨兵-3A)',
    code: 'S3A',
    category: '对地观测',
    missionType: '海洋与陆地观测',
    payloadType: '多光谱/测高',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2016,
    orbitAltitudeKm: 815,
    massKg: 1150,
    resolutionM: 300,
    designLifeYears: 7,
    keywords: ['Sentinel-3', '哨兵3', 'OLCI', 'SLSTR'],
  },
  {
    id: 's3b',
    name: 'Sentinel-3B (哨兵-3B)',
    code: 'S3B',
    category: '对地观测',
    missionType: '海洋与陆地观测',
    payloadType: '多光谱/测高',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2018,
    orbitAltitudeKm: 815,
    massKg: 1150,
    resolutionM: 300,
    designLifeYears: 7,
    keywords: ['Sentinel-3', '哨兵3', 'OLCI', 'SLSTR'],
  },
  {
    id: 'landsat8',
    name: 'Landsat 8',
    code: 'L8',
    category: '对地观测',
    missionType: '陆地成像',
    payloadType: '多光谱成像',
    orbitType: 'SSO',
    agencies: ['NASA', 'USGS'],
    region: '美国',
    launchYear: 2013,
    orbitAltitudeKm: 705,
    inclinationDeg: 98.2,
    massKg: 2782,
    designLifeYears: 5,
    keywords: ['Landsat', '陆地卫星', 'OLI', 'TIRS'],
  },
  {
    id: 'landsat9',
    name: 'Landsat 9',
    code: 'L9',
    category: '对地观测',
    missionType: '陆地成像',
    payloadType: '多光谱成像',
    orbitType: 'SSO',
    agencies: ['NASA', 'USGS'],
    region: '美国',
    launchYear: 2021,
    orbitAltitudeKm: 705,
    inclinationDeg: 98.2,
    designLifeYears: 5,
    keywords: ['Landsat', '陆地卫星', 'OLI-2', 'TIRS-2'],
  },
  {
    id: 'terra',
    name: 'Terra (EOS AM-1)',
    code: 'TERRA',
    category: '对地观测',
    missionType: '地球系统观测',
    payloadType: '多传感器',
    orbitType: 'SSO',
    agencies: ['NASA'],
    region: '美国',
    launchYear: 1999,
    orbitAltitudeKm: 705,
    inclinationDeg: 98.5,
    massKg: 5190,
    keywords: ['Terra', 'MODIS', 'CERES', 'MISR'],
  },
  {
    id: 'aqua',
    name: 'Aqua (EOS PM-1)',
    code: 'AQUA',
    category: '对地观测',
    missionType: '水循环与气候',
    payloadType: '多传感器',
    orbitType: 'SSO',
    agencies: ['NASA'],
    region: '美国',
    launchYear: 2002,
    orbitAltitudeKm: 705,
    inclinationDeg: 98.2,
    massKg: 2934,
    powerW: 4860,
    designLifeYears: 6,
    keywords: ['Aqua', 'MODIS', 'CERES', 'AIRS'],
  },
  {
    id: 'suomi-npp',
    name: 'Suomi NPP',
    code: 'SNPP',
    category: '气象',
    missionType: '气象/气候观测',
    payloadType: '多光谱辐射计',
    orbitType: 'SSO',
    agencies: ['NASA', 'NOAA'],
    region: '美国',
    launchYear: 2011,
    orbitAltitudeKm: 824,
    inclinationDeg: 97.1,
    resolutionM: 375,
    designLifeYears: 5,
    keywords: ['VIIRS', 'CrIS', 'ATMS'],
  },
  {
    id: 'noaa-20',
    name: 'NOAA-20 (JPSS-1)',
    code: 'NOAA-20',
    category: '气象',
    missionType: '气象/气候观测',
    payloadType: '多光谱辐射计',
    orbitType: 'SSO',
    agencies: ['NOAA', 'NASA'],
    region: '美国',
    launchYear: 2017,
    orbitAltitudeKm: 833,
    inclinationDeg: 98.79,
    designLifeYears: 7,
    keywords: ['JPSS', 'VIIRS', 'CrIS', 'ATMS'],
  },
  {
    id: 'goes-16',
    name: 'GOES-16',
    code: 'GOES-16',
    category: '气象',
    missionType: '地球静止气象成像',
    payloadType: '多通道成像(ABI)',
    orbitType: 'GEO',
    agencies: ['NOAA', 'NASA'],
    region: '美国',
    launchYear: 2016,
    orbitAltitudeKm: 35800,
    massKg: 5192,
    resolutionM: 500,
    keywords: ['GOES-R', 'ABI', 'GLM'],
  },
  {
    id: 'goes-17',
    name: 'GOES-17',
    code: 'GOES-17',
    category: '气象',
    missionType: '地球静止气象成像',
    payloadType: '多通道成像(ABI)',
    orbitType: 'GEO',
    agencies: ['NOAA', 'NASA'],
    region: '美国',
    launchYear: 2018,
    orbitAltitudeKm: 35800,
    massKg: 5192,
    resolutionM: 500,
    keywords: ['GOES-S', 'ABI', 'GLM'],
  },
  {
    id: 'goes-18',
    name: 'GOES-18',
    code: 'GOES-18',
    category: '气象',
    missionType: '地球静止气象成像',
    payloadType: '多通道成像(ABI)',
    orbitType: 'GEO',
    agencies: ['NOAA', 'NASA'],
    region: '美国',
    launchYear: 2022,
    orbitAltitudeKm: 35800,
    massKg: 5192,
    resolutionM: 500,
    keywords: ['GOES-T', 'ABI', 'GLM'],
  },
  {
    id: 'himawari-8',
    name: 'Himawari-8 (向日葵-8号)',
    code: 'HIM-8',
    category: '气象',
    missionType: '地球静止气象成像',
    payloadType: 'AHI',
    orbitType: 'GEO',
    agencies: ['JMA'],
    region: '日本',
    launchYear: 2014,
    orbitAltitudeKm: 35800,
    keywords: ['Himawari', 'AHI', '向日葵'],
  },
  {
    id: 'himawari-9',
    name: 'Himawari-9 (向日葵-9号)',
    code: 'HIM-9',
    category: '气象',
    missionType: '地球静止气象成像',
    payloadType: 'AHI',
    orbitType: 'GEO',
    agencies: ['JMA'],
    region: '日本',
    launchYear: 2016,
    orbitAltitudeKm: 35800,
    keywords: ['Himawari', 'AHI', '向日葵'],
  },
  {
    id: 'jason-3',
    name: 'Jason-3',
    code: 'J3',
    category: '海洋测高',
    missionType: '海面高度测量',
    payloadType: '雷达测高',
    orbitType: 'LEO',
    agencies: ['NOAA', 'NASA', 'CNES', 'EUMETSAT'],
    region: '国际',
    launchYear: 2016,
    orbitAltitudeKm: 1336,
    inclinationDeg: 66,
    keywords: ['Altimeter', 'Sea Level'],
  },
  {
    id: 'sentinel-6',
    name: 'Sentinel-6 Michael Freilich',
    code: 'S6-MF',
    category: '海洋测高',
    missionType: '海平面测高',
    payloadType: '雷达测高',
    orbitType: 'LEO',
    agencies: ['ESA', 'EUMETSAT', 'NASA', 'NOAA', 'CNES'],
    region: '国际',
    launchYear: 2020,
    orbitAltitudeKm: 1336,
    inclinationDeg: 66,
    massKg: 1192,
    designLifeYears: 5.5,
    keywords: ['Sentinel-6', 'Jason-CS', 'Altimeter'],
  },
  {
    id: 'icesat-2',
    name: 'ICESat-2',
    code: 'ICESAT-2',
    category: '冰冻圈',
    missionType: '激光测高',
    payloadType: '激光高度计',
    orbitType: 'LEO',
    agencies: ['NASA'],
    region: '美国',
    launchYear: 2018,
    orbitAltitudeKm: 500,
    inclinationDeg: 92,
    powerW: 1320,
    designLifeYears: 3,
    keywords: ['ATLAS', 'Laser Altimeter'],
  },
  {
    id: 'smap',
    name: 'SMAP (Soil Moisture Active Passive)',
    code: 'SMAP',
    category: '水文/土壤',
    missionType: '土壤湿度监测',
    payloadType: '雷达/辐射计',
    orbitType: 'SSO',
    agencies: ['NASA'],
    region: '美国',
    launchYear: 2015,
    orbitAltitudeKm: 685,
    massKg: 946,
    resolutionM: 1000,
    keywords: ['Soil Moisture', 'Radar', 'Radiometer'],
  },
  {
    id: 'swot',
    name: 'SWOT (Surface Water and Ocean Topography)',
    code: 'SWOT',
    category: '水文/海洋测高',
    missionType: '水体测高',
    payloadType: '干涉雷达测高',
    orbitType: 'LEO',
    agencies: ['NASA', 'CNES', 'CSA', 'UKSA'],
    region: '国际',
    launchYear: 2022,
    orbitAltitudeKm: 890.582,
    inclinationDeg: 77.6,
    massKg: 2200,
    powerW: 8000,
    designLifeYears: 3,
    keywords: ['KaRIn', 'Altimeter', 'Hydrology'],
  },
  {
    id: 's5p',
    name: 'Sentinel-5P (哨兵-5P)',
    code: 'S5P',
    category: '大气成分',
    missionType: '大气成分监测',
    payloadType: 'TROPOMI',
    orbitType: 'SSO',
    agencies: ['ESA', '欧盟/哥白尼'],
    region: '欧洲',
    launchYear: 2017,
    orbitAltitudeKm: 824,
    massKg: 820,
    designLifeYears: 7,
    keywords: ['Sentinel-5P', 'TROPOMI', 'Copernicus'],
  },
  {
    id: 'metop-a',
    name: 'MetOp-A',
    code: 'METOP-A',
    category: '气象',
    missionType: '全球气象监测',
    payloadType: '多传感器',
    orbitType: 'SSO',
    agencies: ['EUMETSAT', 'ESA'],
    region: '欧洲',
    launchYear: 2006,
    keywords: ['MetOp', 'Polar', 'Weather'],
  },
  {
    id: 'metop-b',
    name: 'MetOp-B',
    code: 'METOP-B',
    category: '气象',
    missionType: '全球气象监测',
    payloadType: '多传感器',
    orbitType: 'SSO',
    agencies: ['EUMETSAT', 'ESA'],
    region: '欧洲',
    launchYear: 2012,
    orbitAltitudeKm: 817,
    keywords: ['MetOp', 'Polar', 'Weather'],
  },
  {
    id: 'metop-c',
    name: 'MetOp-C',
    code: 'METOP-C',
    category: '气象',
    missionType: '全球气象监测',
    payloadType: '多传感器',
    orbitType: 'SSO',
    agencies: ['EUMETSAT', 'ESA'],
    region: '欧洲',
    launchYear: 2018,
    orbitAltitudeKm: 817,
    keywords: ['MetOp', 'Polar', 'Weather'],
  },
  {
    id: 'aura',
    name: 'Aura (EOS)',
    code: 'AURA',
    category: '大气成分',
    missionType: '大气化学/臭氧监测',
    payloadType: '多传感器',
    orbitType: 'SSO',
    agencies: ['NASA'],
    region: '美国',
    launchYear: 2004,
    orbitAltitudeKm: 705,
    inclinationDeg: 98.2,
    keywords: ['EOS', 'OMI', 'MLS', 'TES'],
  },
  {
    id: 'oco-2',
    name: 'OCO-2',
    code: 'OCO-2',
    category: '大气成分',
    missionType: '二氧化碳监测',
    payloadType: '光谱仪',
    orbitType: 'LEO',
    agencies: ['NASA', 'JPL'],
    region: '美国',
    launchYear: 2014,
    keywords: ['CO2', 'OCO'],
  },
  {
    id: 'gpm-core',
    name: 'GPM Core Observatory',
    code: 'GPM',
    category: '降水',
    missionType: '全球降水测量',
    payloadType: 'DPR/GMI',
    orbitType: 'LEO',
    agencies: ['NASA', 'JAXA'],
    region: '国际',
    launchYear: 2014,
    orbitAltitudeKm: 407,
    inclinationDeg: 65,
    keywords: ['Precipitation', 'Radar', 'Microwave'],
  },
  {
    id: 'trmm',
    name: 'TRMM (Tropical Rainfall Measuring Mission)',
    code: 'TRMM',
    category: '降水',
    missionType: '热带降水测量',
    payloadType: '雷达/微波/闪电',
    orbitType: 'LEO',
    agencies: ['NASA', 'JAXA'],
    region: '国际',
    launchYear: 1997,
    orbitAltitudeKm: 400,
    keywords: ['Rainfall', 'Tropical', 'PR', 'TMI'],
  },
  {
    id: 'grace',
    name: 'GRACE',
    code: 'GRACE',
    category: '重力场',
    missionType: '地球重力场测量',
    payloadType: '双星测距',
    orbitType: 'LEO',
    agencies: ['NASA', 'DLR', 'GFZ'],
    region: '国际',
    launchYear: 2002,
    orbitAltitudeKm: 485,
    keywords: ['Gravity', 'Twin', 'GRACE'],
  },
  {
    id: 'grace-fo',
    name: 'GRACE-FO',
    code: 'GRACE-FO',
    category: '重力场',
    missionType: '重力场后继任务',
    payloadType: '双星测距',
    orbitType: 'LEO',
    agencies: ['NASA', 'GFZ'],
    region: '国际',
    launchYear: 2018,
    keywords: ['Gravity', 'Follow-On'],
  },
  {
    id: 'cloudsat',
    name: 'CloudSat',
    code: 'CLOUDSAT',
    category: '云与降水',
    missionType: '云层结构探测',
    payloadType: '云雷达',
    orbitType: 'SSO',
    agencies: ['NASA', 'CSA'],
    region: '国际',
    launchYear: 2006,
    orbitAltitudeKm: 705,
    inclinationDeg: 98.2,
    keywords: ['Cloud Radar', 'A-Train'],
  },
  {
    id: 'calipso',
    name: 'CALIPSO',
    code: 'CALIPSO',
    category: '云与气溶胶',
    missionType: '激光雷达气溶胶/云观测',
    payloadType: '激光雷达',
    orbitType: 'SSO',
    agencies: ['NASA', 'CNES'],
    region: '国际',
    launchYear: 2006,
    keywords: ['CALIOP', 'Lidar', 'A-Train'],
  },
];
