/**
 * Story 2.9: Mock Satellite Application Library Data
 * Provides mock application data for APP nodes
 * Enhanced with rich satellite-specific outputs for preview
 */

import type { AppLibraryEntry } from '@cdm/types';

export const SATELLITE_APPS: AppLibraryEntry[] = [
  {
    id: 'sat-orbit-designer',
    name: 'Orbit Designer Pro',
    description: '专业轨道设计与分析工具，支持多种轨道类型计算',
    category: '轨道设计',
    icon: 'orbit',
    version: '2.1.0',
    executionType: 'webapi',
    apiEndpoint: '/api/mock/orbit-calc',
    defaultInputs: [
      { key: '轨道高度', type: 'number', required: true },
      { key: '轨道倾角', type: 'number', required: true },
      { key: '偏心率', type: 'number', required: false },
      { key: '升交点赤经', type: 'number', required: false },
    ],
    defaultOutputs: [
      { key: '轨道周期', type: 'text' },
      { key: '轨道高度', type: 'text' },
      { key: '轨道倾角', type: 'text' },
      { key: '轨道速度', type: 'text' },
      { key: '地面覆盖', type: 'text' },
      { key: '轨道根数报告', type: 'file', mimeType: 'application/pdf' },
      { key: '星历数据', type: 'file', mimeType: 'application/json' },
    ],
  },
  {
    id: 'sat-thermal-analysis',
    name: 'Thermal Analysis Tool',
    description: '卫星热环境模拟与分析',
    category: '热分析',
    icon: 'thermometer',
    version: '1.5.3',
    executionType: 'local',
    protocolScheme: 'thermal-sim://',
    defaultInputs: [
      { key: '卫星模型', type: 'file', required: true },
      { key: '轨道数据', type: 'file', required: true },
      { key: '分析时长', type: 'number', required: false },
    ],
    defaultOutputs: [
      { key: '温度范围', type: 'text' },
      { key: '分析状态', type: 'text' },
      { key: '温度分布图', type: 'file', mimeType: 'image/png' },
      { key: '热分析报告', type: 'file', mimeType: 'application/pdf' },
      { key: '热控数据', type: 'file', mimeType: 'text/csv' },
    ],
  },
  {
    id: 'sat-signal-process',
    name: 'Signal Process v2',
    description: '卫星通信信号处理与分析',
    category: '信号处理',
    icon: 'radio',
    version: '2.0.1',
    executionType: 'webapi',
    apiEndpoint: '/api/mock/signal-process',
    defaultInputs: [
      { key: '信号数据', type: 'file', required: true },
      { key: '频段', type: 'text', required: true },
      { key: '调制方式', type: 'text', required: false },
    ],
    defaultOutputs: [
      { key: '载噪比', type: 'text' },
      { key: '误码率', type: 'text' },
      { key: '数传速率', type: 'text' },
      { key: '处理结果', type: 'file', mimeType: 'application/octet-stream' },
      { key: '频谱分析图', type: 'file', mimeType: 'image/png' },
      { key: '分析报告', type: 'text' },
    ],
  },
  {
    id: 'sat-power-budget',
    name: 'Power Budget Calculator',
    description: '能源预算计算与优化',
    category: '能源管理',
    icon: 'battery',
    version: '1.2.0',
    executionType: 'webapi',
    apiEndpoint: '/api/mock/power-calc',
    defaultInputs: [
      { key: '太阳帆板面积', type: 'number', required: true },
      { key: '负载曲线', type: 'file', required: true },
      { key: '轨道参数', type: 'text', required: true },
    ],
    defaultOutputs: [
      { key: '功率平衡', type: 'text' },
      { key: '太阳能帆板', type: 'text' },
      { key: '蓄电池状态', type: 'text' },
      { key: '整星功耗', type: 'text' },
      { key: '功率预算报告', type: 'file', mimeType: 'application/pdf' },
      { key: '功率曲线数据', type: 'file', mimeType: 'text/csv' },
    ],
  },
  {
    id: 'sat-link-budget',
    name: 'Link Budget Analyzer',
    description: '通信链路预算分析',
    category: '通信链路',
    icon: 'antenna',
    version: '3.0.0',
    executionType: 'webapi',
    apiEndpoint: '/api/mock/link-budget',
    defaultInputs: [
      { key: '发射功率', type: 'number', required: true },
      { key: '天线增益', type: 'number', required: true },
      { key: '通信距离', type: 'number', required: true },
      { key: '工作频率', type: 'number', required: true },
    ],
    defaultOutputs: [
      { key: '链路余量', type: 'text' },
      { key: 'EIRP', type: 'text' },
      { key: 'G/T品质因数', type: 'text' },
      { key: '载噪比', type: 'text' },
      { key: '传输速率', type: 'text' },
      { key: '链路预算报告', type: 'file', mimeType: 'application/pdf' },
    ],
  },
  {
    id: 'sat-structural-analysis',
    name: 'Structural Analyzer',
    description: '卫星结构强度与振动分析',
    category: '结构分析',
    icon: 'box',
    version: '2.0.0',
    executionType: 'local',
    protocolScheme: 'structural-sim://',
    defaultInputs: [
      { key: 'CAD模型', type: 'file', required: true },
      { key: '材料属性', type: 'file', required: true },
      { key: '载荷工况', type: 'text', required: true },
    ],
    defaultOutputs: [
      { key: '整星质量', type: 'text' },
      { key: '固有频率', type: 'text' },
      { key: '分析状态', type: 'text' },
      { key: '应力分析报告', type: 'file', mimeType: 'application/pdf' },
      { key: '变形云图', type: 'file', mimeType: 'image/png' },
      { key: '模态分析数据', type: 'file', mimeType: 'text/csv' },
    ],
  },
  {
    id: 'sat-attitude-control',
    name: 'Attitude Control Designer',
    description: '卫星姿态控制系统设计与仿真',
    category: '姿态控制',
    icon: 'compass',
    version: '1.8.0',
    executionType: 'webapi',
    apiEndpoint: '/api/mock/attitude-control',
    defaultInputs: [
      { key: '转动惯量', type: 'file', required: true },
      { key: '执行机构配置', type: 'text', required: true },
      { key: '指向目标', type: 'text', required: true },
    ],
    defaultOutputs: [
      { key: '姿态精度', type: 'text' },
      { key: '姿态机动能力', type: 'text' },
      { key: '稳定性状态', type: 'text' },
      { key: '控制响应曲线', type: 'file', mimeType: 'image/png' },
      { key: '姿控参数报告', type: 'file', mimeType: 'application/pdf' },
    ],
  },
  {
    id: 'sat-mission-planner',
    name: 'Mission Planner',
    description: '卫星任务规划与调度',
    category: '任务规划',
    icon: 'calendar',
    version: '4.0.0',
    executionType: 'webapi',
    apiEndpoint: '/api/mock/mission-plan',
    defaultInputs: [
      { key: '轨道参数', type: 'file', required: true },
      { key: '地面站网络', type: 'file', required: true },
      { key: '任务时长', type: 'number', required: true },
    ],
    defaultOutputs: [
      { key: '覆盖分析', type: 'text' },
      { key: '任务规划状态', type: 'text' },
      { key: '任务时间表', type: 'file', mimeType: 'application/json' },
      { key: '覆盖分析报告', type: 'file', mimeType: 'application/pdf' },
      { key: '可视窗口数据', type: 'file', mimeType: 'text/csv' },
    ],
  },
  {
    id: 'sat-stk-interface',
    name: 'STK 接口',
    description: 'AGI STK 软件接口，支持场景导入导出',
    category: '轨道设计',
    icon: 'orbit',
    version: '12.0.0',
    executionType: 'local',
    protocolScheme: 'stk://',
    defaultInputs: [
      { key: 'STK场景文件', type: 'file', required: true },
      { key: '仿真时长', type: 'number', required: true },
      { key: '输出间隔', type: 'number', required: false },
    ],
    defaultOutputs: [
      { key: '轨道周期', type: 'text' },
      { key: '轨道高度', type: 'text' },
      { key: '偏心率', type: 'text' },
      { key: '覆盖分析', type: 'text' },
      { key: 'STK报告', type: 'file', mimeType: 'application/pdf' },
      { key: '星历导出', type: 'file', mimeType: 'text/plain' },
      { key: '可视化截图', type: 'file', mimeType: 'image/png' },
    ],
  },
  {
    id: 'sat-propulsion-design',
    name: 'Propulsion Designer',
    description: '推进系统设计与性能分析',
    category: '推进系统',
    icon: 'rocket',
    version: '2.5.0',
    executionType: 'webapi',
    apiEndpoint: '/api/mock/propulsion',
    defaultInputs: [
      { key: '推进剂类型', type: 'text', required: true },
      { key: '速度增量需求', type: 'number', required: true },
      { key: '干重', type: 'number', required: true },
    ],
    defaultOutputs: [
      { key: 'DV预算', type: 'text' },
      { key: '比冲', type: 'text' },
      { key: '推进剂质量', type: 'text' },
      { key: '整星质量', type: 'text' },
      { key: '推进系统报告', type: 'file', mimeType: 'application/pdf' },
    ],
  },
];

